### ISSUE TITLE
Bug Summary

### ISSUE THREAD

**Issue by Steffengreiner** [qbicsoftware/qube-cli#242]
**Describe the bug**

`sync_project.yml` doesn't specify the token during `actions/checkout@v2` in the TEMPLATE Branches. 
This leads to a termination of the Github action during the checkout process. 

**Expected behavior**
Please specify the token in the 'actions/checkout@v2' step in the sync_project.yml for the template branch as follows: 
`token: '${{ secrets.JOHNNY_Q5_REPORTS_TOKEN  }}'`

**Additional context**
We noticed this in the data-model-lib [Template Branch](https://github.com/qbicsoftware/data-model-lib/blob/TEMPLATE/.github/workflows/sync_project.yml) and SF fixed in on the [master branch.](https://github.com/qbicsoftware/data-model-lib/blob/master/.github/workflows/sync_project.yml)

**Comment by sven1103** [comment]
That is the correct layout:


```
name: Sync qube project

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.8

        - name: Install qube
          run: pip install qube

        - uses: actions/checkout@v2
          with:
              fetch-depth: 0
              token: '${{ secrets.JOHNNY_Q5_REPORTS_TOKEN  }}'
          name: Check out source-code repository

        - uses: oleksiyrudenko/gha-git-credentials@v2-latest
          with:
              name: 'JohnnyQ5'
              email: 'support@qbic.zendesk.com'
              actor: 'JohnnyQ5'
              token: '${{ secrets.JOHNNY_Q5_REPORTS_TOKEN}}'

        - name: Sync project
          run: qube sync . ${{ secrets.JOHNNY_Q5_REPORTS_TOKEN  }} JohnnyQ5

```
